---
- name: Install SSSD and related
  apt:
    name: ['sssd', 'libpam-sss', 'libnss-sss']
    state: present

- name: Copy sssd.conf
  template: src=sssd.conf.j2 dest=/etc/sssd/sssd.conf
  notify: restart sssd

- name: copy PAM mkhomedir config
  template: src=pam-configs-my_mkhomedir.conf.j2 dest=/usr/share/pam-configs/my_mkhomedir
  notify: restart sssd

- name: Ensure SSSD is started and enabled on boot
  service: name=sssd state=started enabled=yes

- name: Enable new PAM config
  command: "/usr/sbin/pam-auth-update --package"

#- name: Check if authconfig did a previous run
#  command: "/bin/egrep '^auth.*success.*pam_sss.so' /etc/pam.d/common-auth"
#  register: authconfig_run
#  failed_when: authconfig_run.rc != 0
#  changed_when: false
#  ignore_errors: true

#- name: Run authconfig
#  shell: /usr/sbin/authconfig --update --enablesssd --enablesssdauth --enablemkhomedir --nostart
#  when: authconfig_run is failed
